[build-system]
build-backend = 'setuptools.build_meta'
requires = [ "setuptools>=62.0.0", "setuptools_scm", "pip>=19.0.0", "wheel", "numpy", "amuse-devel" ]

[tool.setuptools_scm]
write_to = "src/omuse/version.py"
