name: pop-omuse

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-pop-omuse
  cancel-in-progress: true

jobs:

  build-deps:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel setuptools_scm amuse-framework
