name: pop-omuse

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-pop-omuse
  cancel-in-progress: true

jobs:

  Formatting:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        ref: main

    - name: Set up JDK
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
  
    - name: cache poetry
      uses: actions/cache@v3
      with:
        key: poetry-1.6.0

    - name: install system deps
      run: |
        sudo apt-get install libopenmpi-dev

    - name: Install amuse-devel
      run: |
        git clone https://github.com/amusecode/amuse
        cd amuse
        pip install -e .
  
    - name: install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.6.0
        poetry config virtualenvs.create "true"
        poetry config virtualenvs.in-project "true"
  
    - name: install deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cp .github/workflows/support_ci/pyproject.toml ./Submodules/omuse/
        cp .github/workflows/support_ci/setup.py ./Submodules/omuse/
        poetry install --no-interaction --no-root
  
    - name: Formatting with black
      run: poetry run black --check .
  
    - name: Sort import
      run: poetry run isort --check-only --diff .
  
    - name: Lint with flake8
      run: poetry run flake8 --exclude "Submodules, amuse, .venv, .github" .

  build-deps:
    strategy:
      matrix:
        os: [ macos-latest ]

    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}
      ##needs: Formatting

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        ref: main

    - name: Set up JDK
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: cache poetry
      uses: actions/cache@v3
      with:
        path: ~/.local-${{ matrix.os }}
        key: poetry-1.6.0

    - name: install system deps [macOS]
      if: runner.os == 'macOS'
      run: |
        brew install openmpi || true
        ln -s /usr/local/bin/gfortran-13 /usr/local/bin/gfortran
        brew install netcdf netcdf-fortran || true

    - name: install system deps [ubuntu]
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install libopenmpi-dev
        sudo apt-get install libnetcdf-dev

    - name: Install amuse-devel
      run: |
        git clone https://github.com/amusecode/amuse
        cd amuse
        pip install -e .
        if [ "${{ matrix.os }}" == 'macos-latest' ]; then \
          cat ./config.mk
          sed -i '' "s#NETCDF_LIBS*#NETCDF_LIBS=-L/usr/local/Cellar/netcdf/4.9.2_1/lib -lnetcdf#" ./config.mk
          sed -i '' "s#NETCDFF_FLAGS*#NETCDFF_FLAGS=-I/opt/homebrew/Cellar/netcdf-fortran/4.6.1/include#" ./config.mk
          sed -i '' "s#NETCDFF_LIBS*#NETCDFF_LIBS=-L/opt/homebrew/Cellar/netcdf-fortran/4.6.1/lib -lnetcdff#" ./config.mk
          cat ./config.mk
        fi
        if [ "${{ matrix.os }}" == 'ubuntu-latest' ]; then \
          which ncdump
        fi

    - name: install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.6.0
        if [ "${{ matrix.os }}" == 'macos-latest' ]; then \
          echo "/Users/runner/.local/bin" >> $GITHUB_PATH
          export PATH="/Users/runner/.local/bin:$PATH"
        fi
        poetry config virtualenvs.create "true"
        poetry config virtualenvs.in-project "true"

    - name: install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cp .github/workflows/support_ci/pyproject.toml ./Submodules/omuse/
        cp .github/workflows/support_ci/setup.py ./Submodules/omuse/
        poetry install --no-interaction --no-root

    - name: build pop workers
      run: |
        cat .github/workflows/support_ci/makefile_help >> ./Submodules/omuse/src/omuse/community/pop/Makefile
        cd ./Submodules/omuse/src/omuse/community/pop
        make help
        pip list
        make DOWNLOAD_CODES=1 -j4

    - name: install tamspop
      run: poetry install --no-interaction

    - name: run tamspop tests
      run: poetry run pytest ./tests
