name: pop-omuse

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-pop-omuse
  cancel-in-progress: true

jobs:

  build-deps:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: cache poetry
      uses: actions/cache@v3
      with:
        path: ~/.local-${{ matrix.os }}
        key: poetry-1.6.0

    - name: install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.6.0
        poetry config virtualenvs.create "true"
        poetry config virtualenvs.in-project "true"
        poetry config --list
